# Generated by Django 4.1.6 on 2023-02-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='home1',
        ),
    ]
