# Generated by Django 4.1.6 on 2023-02-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_home_home1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home1',
            old_name='desc',
            new_name='message1',
        ),
    ]
