# Generated by Django 4.1.6 on 2023-02-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_login1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login1',
            new_name='loginmy',
        ),
    ]
