# Generated by Django 4.1.6 on 2023-02-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_content_post_body_post_author_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetail',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostDetail',
        ),
    ]
