# Generated by Django 4.1.6 on 2023-02-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_paragraph_section_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='paragraph',
            field=models.TextField(default=''),
        ),
    ]
