# Generated by Django 4.1.6 on 2023-02-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_blogpost_content1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='URL',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
