# Generated by Django 4.1.6 on 2023-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_blogpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='img_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
