# Generated by Django 4.1.6 on 2023-02-24 11:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_blogpost_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
